### ISSUE TITLE
Logo Proposal for Nebulator

### ISSUE THREAD

**Issue by area55git** [cepthomas/Nebulator#1]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project Nebulator.

I will be pleased to collaborate with you.

**Comment by cepthomas** [comment]
Interesting. I'll think about it.

**Comment by area55git** [comment]
I can present you a proposal, do you have something in mind that you would like to use in the design of the logo?

**Comment by cepthomas** [comment]
Well if you want to have fun with it, go ahead.

Nebulator is named for a similar application a friend made called Nebula.
It refers to the space object. But nebulator would be a thing that makes
nebulas maybe?

Try google "nebula icon".



Chris
